
--CRUD : 데이터를 기본 처리 가능 --
-- C : CREATE 	- INSERT 
-- R : READ 	- SELECT 
-- U : UPDATE 	- UPDATE
-- D : DELETE 	- DELETE 

--DDL( CREATE, ALTER, DROP )
--CREATE : 데이터베이스 객체 생성
--ALTER  : 생성한 객체를 수정
--DROP   : 생성한 객체를 삭제

--ALTER
DROP TABLE DEPT_COPY;

CREATE TABLE DEPT_COPY
AS SELECT * FROM DEPARTMENT;

SELECT * FROM DEPT_COPY;

--DEPT_COPY 테이블에 컬럼 추가
ALTER TABLE DEPT_COPY ADD(LNAME VARCHAR(20));

--DEPT_COPY 테이블에 컬럼 삭제
ALTER TABLE DEPT_COPY DROP COLUMN LNAME;

--기본값 적용하여 추가
ALTER TABLE DEPT_COPY ADD (LNAME VARCHAR(20) DEFAULT '한국');

SELECT * FROM DEPT_COPY;

--없는 테이블 제거시 오류발생
DROP TABLE DEPT_COPY2;

CREATE TABLE DEPT_COPY2
AS SELECT * FROM DEPT_COPY;

SELECT * FROM DEPT_COPY2;

--DEPT_ID에 기본키 제약조건 추가
ALTER TABLE DEPT_COPY2 
ADD CONSTRAINT PK_DEPT_CP2 PRIMARY KEY(DEPT_ID);

--DEPT_TITLE에 고유값 제약조건 추가
ALTER TABLE DEPT_COPY2
ADD CONSTRAINT UK_DEPT_TITLE UNIQUE(DEPT_TITLE);

--LNAME에 필수 입력사항에 대한 제약조건 추가 (NOT NULL은 컬럼수준에서만 선언 가능 / 테이블수준 불가능)
ALTER TABLE DEPT_COPY2
MODIFY LNAME CONSTRAINT NN_DEPT_LNAME NOT NULL;

SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'DEPT_COPY2';


--ORA-12899: value too large for column "KH"."DEPT_COPY2"."DEPT_ID"
INSERT INTO DEPT_COPY2
VALUES('D10','샘플부서','L1','한국');

--컬럼의 자료형 수정 (컬럼의 크기나 자료형변경시 기존에 들어간 값들 고려)
ALTER TABLE DEPT_COPY2
MODIFY DEPT_ID VARCHAR(10)
MODIFY DEPT_TITLE VARCHAR(30);

--ORA-01441: cannot decrease column length because some value is too big
ALTER TABLE DEPT_COPY2
MODIFY DEPT_TITLE VARCHAR(3);

--컬럼의 기본값 변경
ALTER TABLE DEPT_COPY2
MODIFY LNAME VARCHAR(20) DEFAULT '대한민국';

INSERT INTO DEPT_COPY2
VALUES('D11','교육부','L1',DEFAULT);

SELECT * FROM DEPT_COPY2;

--컬럼의 이름 변경
ALTER TABLE DEPT_COPY2
RENAME COLUMN DEPT_TITLE TO DEPT_NAME;

SELECT * FROM DEPT_COPY2;

--테이블의 이름 변경
ALTER TABLE DEPT_COPY2
RENAME TO DEPT_COPY_SECOND;

SELECT * FROM DEPT_COPY_SECOND;
SELECT * FROM DEPT_COPY2;

--테이블 이름 변경 한정하여 짧게 줄여 쓸 수 있다.
RENAME DEPT_COPY_SECOND TO DEPT_COPY2;

--이후 라인 AUTO COMMIT 해제 상태

--COMMIT 과 ROLLBACK
COMMIT;
SELECT * FROM DEPT_COPY2;

INSERT INTO DEPT_COPY2
VALUES('D13','소프트웨어팀','L1',DEFAULT);

SELECT * FROM DEPT_COPY2;

ROLLBACK;  --COMMIT 이전 상태로 돌아감


--DDL 명령어는 사용자 계정 설정 정보에 대한 하나의 연결객체로 처리하여
--COMMIT/ROLLBACK이 불가능 (COMMIT/ROLLBACK은 테이블에 대한 수정)
--또한 이전에 DML을 사용한 후에 DDL 명령어를 사용하면
--그 이전까지의 데이터 조작 내용이 자동으로 COMMIT 처리 됨 
ALTER TABLE DEPT_COPY2
DROP COLUMN LOCATION_ID;

SELECT * FROM DEPT_COPY2;

ROLLBACK;  --DROP

ALTER TABLE DEPT_COPY2 DROP COLUMN DEPT_NAME;
ALTER TABLE DEPT_COPY2 DROP COLUMN LNAME;
--ORA-12983: cannot drop all columns in a table
--컬럼 삭제 시에는 반드시 하나 이상의 컬럼이 존재해야 한다.
ALTER TABLE DEPT_COPY2 DROP COLUMN DEPT_ID;

SELECT * FROM DEPT_COPY;

--()를 사용하여 컬럼 삭제
ALTER TABLE DEPT_COPY DROP (LNAME);

--여러 컬럼 한번에 삭제
ALTER TABLE DEPT_COPY DROP (DEPT_TITLE, LOCATION_ID);

--제약조건 삭제하기
CREATE TABLE CONST_TAB(
	EID CHAR(2),
	ENAME VARCHAR2(15) NOT NULL, -- 컬럼레벨
	AGE NUMBER NOT NULL,
	DEPT CHAR(5),
	--테이블 레벨
	CONSTRAINT PK_TAB PRIMARY KEY(EID),
	CONSTRAINT UK_TAB UNIQUE(ENAME),
	CONSTRAINT CK_TAB CHECK(AGE>0),
	CONSTRAINT FK_TAB FOREIGN KEY(DEPT) REFERENCES DEPARTMENT ON DELETE CASCADE
);

SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME='CONST_TAB';

--제약조건 삭제
ALTER TABLE CONST_TAB
DROP CONSTRAINT CK_TAB;

--NOT NULL 을 제외한 CONST_TAB의 제약조건을 삭제
ALTER TABLE CONST_TAB
DROP CONSTRAINT UK_TAB;

ALTER TABLE CONST_TAB
DROP CONSTRAINT PK_TAB;

ALTER TABLE CONST_TAB
DROP CONSTRAINT FK_TAB;

SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME='CONST_TAB';


--NOT NULL 삭제하기
ALTER TABLE CONST_TAB
DROP CONSTRAINT SYS_C007108;

ALTER TABLE CONST_TAB 
MODIFY (AGE NULL);